# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7962cfb321a4a795e525605c5044f43e77639852bc2c6266a56404908f403bbb4b503ec287658bb5971b30ab1b12121a438ed4e729a91f95bbdcf3071edff3d2

test:
  secret_key_base: 65fe38b1c40ea1cc1b8b84a01c278c2e8b4cc09d6cce96fe139db8e130e4d1f858e5eec87d69d0ab77140c91f6a8e7d66625ba214365f23f0efbb376cfa102de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
